monolog:
  channels: [deprecation]
  handlers:
    deprecation:
      type: rotating_file
      max_files: 1
      path: '%kernel.logs_dir%/%kernel.environment%/deprecation.log'
      level: emergency # don't want any deprecation logs at all
      channels: [deprecation]
    symfony_mailer:
      type:       symfony_mailer
      from_email: 'logger@pms.pms'
      to_email:   'mailpit@pms.pms'
      subject: '[%project.name%] An Error Occurred!'
      level:      warning
      formatter:  monolog.formatter.html
      content_type: text/html
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console", "!deprecation"]
    security:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/%kernel.environment%/security.log"
      level: info
      channels: ["security"]
    main:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/%kernel.environment%/main.log"
      level: info
      channels: [ "!event", "!doctrine", "!security", "!deprecation", "!request"]
    request:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/%kernel.environment%/request.log"
      level: info
      channels: ["request"]
    deduplicated:
      type:    deduplication
      handler: symfony_mailer